TEST_CASES = 12 # The number of test cases
PROGRAM_LEN = 60 # The length of the body program, it should be at least 50

# TEXT is the text memory, DATA is the data memory
# ORIGIN is the base address of the current memory region. ORIGIN must be a "hex" string
# LENGTH is the length of the current memory region, calculated in KiB
[TEXT]
ORIGIN = "0x20000000"
SIZE = 32 # KiB
[DATA]
ORIGIN = "0x22000000"
SIZE = 16 # KiB

# The instructions are supported in the RTG
# You can comment instructions which are not exist in your design
[RV32_INSTRUCTIONS]
V_OPIVV = [
    # Vector Single-Width Integer Add and Subtract
    "vadd.vv",
    "vsub.vv",
    # Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions
    "vadc.vvm",
    "vmadc.vvm",
    "vmadc.vv",
    "vsbc.vvm",
    "vmsbc.vvm",
    "vmsbc.vv",
    # Vector Bitwise Logical Instructions
    "vand.vv",
    "vor.vv",
    "vxor.vv",
    # Vector Single-Width Shift Instructions
    "vsll.vv",
    "vsrl.vv",
    "vsra.vv",
    # Vector Narrowing Integer Right Shift Instructions
    "vnsrl.wv",
    "vnsra.wv",
    # Vector Integer Compare Instructions
    "vmseq.vv",
    "vmsne.vv",
    "vmsltu.vv",
    "vmslt.vv",
    "vmsleu.vv",
    "vmsle.vv",
    # Vector Integer Min/Max Instructions
    "vminu.vv",
    "vmin.vv",
    "vmaxu.vv",
    "vmax.vv",
    # Vector Integer Merge Instructions
    "vmerge.vvm",
    # Vector Integer Move Instructions
    "vmv.v.v",
]

V_OPIVX = [
    # Vector Single-Width Integer Add and Subtract
    "vadd.vx",
    "vsub.vx",
    "vrsub.vx",
    # Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions
    "vadc.vxm",
    "vmadc.vxm",
    "vmadc.vx",
    "vsbc.vxm",
    "vmsbc.vxm",
    "vmsbc.vx",
    # Vector Bitwise Logical Instructions
    "vand.vx",
    "vor.vx",
    "vxor.vx",
    # Vector Single-Width Shift Instructions
    "vsll.vx",
    "vsrl.vx",
    "vsra.vx",
    # Vector Narrowing Integer Right Shift Instructions
    "vnsrl.wx",
    "vnsra.wx",
    # Vector Narrowing Integer Right Shift Instructions
    "vmseq.vx",
    "vmsne.vx",
    "vmsltu.vx",
    "vmslt.vx",
    "vmsleu.vx",
    "vmsle.vx",
    "vmsgtu.vx",
    "vmsgt.vx",
    # Vector Integer Min/Max Instructions
    "vminu.vx",
    "vmin.vx",
    "vmaxu.vx",
    "vmax.vx",
    # Vector Integer Merge Instructions
    "vmerge.vxm",
    # Vector Integer Move Instructions
    "vmv.v.x",
]

V_OPIVI = [
    # Vector Single-Width Integer Add and Subtract
    "vadd.vi",
    "vrsub.vi",
    # Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions
    "vadc.vim",
    "vmadc.vim",
    "vmadc.vi",
    # Vector Bitwise Logical Instructions
    "vand.vi",
    "vor.vi",
    "vxor.vi",
    # Vector Single-Width Shift Instructions
    "vsll.vi",
    "vsrl.vi",
    "vsra.vi",
    # Vector Narrowing Integer Right Shift Instructions
    "vnsrl.wi",
    "vnsra.wi",
    # Vector Integer Compare Instructions
    "vmseq.vi",
    "vmsne.vi",
    "vmsleu.vi",
    "vmsle.vi",
    "vmsgt.vi",
    "vmsgtu.vi",
    # Vector Integer Merge Instructions
    "vmerge.vim",
    # Vector Integer Move Instructions
    "vmv.v.i",
]

V_OPMVV = [
    # Vector Widening Integer Add/Subtract
    "vwaddu.vv",
    "vwsubu.vv",
    "vwadd.vv",
    "vwsub.vv",
    "vwaddu.wv",
    "vwsubu.wv",
    "vwadd.wv",
    "vwsub.wv",
    # Vector Widening Integer Multiply Instructions
    "vwmul.vv",
    "vwmulu.vv",
    "vwmulsu.vv",
    # Vector Widening Integer Multiply-Add Instructions
    "vwmaccu.vv",
    "vwmacc.vv",
    "vwmaccsu.vv",
    # Vector Integer Extension
    "vzext.vf2",
    "vsext.vf2",
    "vzext.vf4",
    "vsext.vf4",
    # Vector Single-Width Integer Multiply-Add Instructions
    "vmacc.vv",
    "vnmsac.vv",
    "vmadd.vv",
    "vnmsub.vv",
    # Vector Single-Width Integer Multiply Instructions
    "vmul.vv",
    "vmulh.vv",
    "vmulhu.vv",
    "vmulhsu.vv",
    # Vector Integer Divide Instructions
    "vdivu.vv",
    "vdiv.vv",
    "vremu.vv",
    "vrem.vv",
]

V_OPMVX = [
    "vwaddu.vx",
    "vwsubu.vx",
    "vwadd.vx",
    "vwsub.vx",
    "vwaddu.wx",
    "vwsubu.wx",
    "vwadd.wx",
    "vwsub.wx",
    "vwmul.vx",
    "vwmulu.vx",
    "vwmulsu.vx",
    "vwmacc.vx",
    "vwmaccsu.vx",
    "vwmaccus.vx",
    "vmacc.vx",
    "vnmsac.vx",
    "vmadd.vx",
    "vnmsub.vx",
    "vmul.vx",
    "vmulh.vx",
    "vmulhu.vx",
    "vmulhsu.vx",
    "vdivu.vx",
    "vdiv.vx",
    "vremu.vx",
    "vrem.vx",
    "vwmaccu.vx",
]

V_OPCFG = [
    "vsetvl",
    "vsetvli",
    "vsetivli",
]

V_OP_UNIT_STRIDE = [
    "vle8.v",
    "vle16.v",
    "vle32.v",
    #
    "vse8.v",
    "vse16.v",
    "vse32.v",
    #
    "vlm.v",
    "vsm.v",
]
V_OP_FAULT_ONLY_FIRST_LOADS = [
    "vle8ff.v",
    "vle16ff.v",
    "vle32ff.v",
]
V_OP_STRIDED = [
    "vlse8.v",
    "vlse16.v",
    "vlse32.v",
    #
    "vsse8.v",
    "vsse16.v",
    "vsse32.v",
]
V_OP_INDEXED = [
    "vluxei8.v",
    "vluxei16.v",
    "vluxei32.v",
    #
    "vloxei8.v",
    "vloxei16.v",
    "vloxei32.v",
    #
    "vsuxei8.v",
    "vsuxei16.v",
    "vsuxei32.v",
    #
    "vsoxei8.v",
    "vsoxei16.v",
    "vsoxei32.v",
]

I_OP_R = [
    "add",
    "sub",
    "sll",
    "slt",
    "sltu",
    "xor",
    "srl",
    "sra",
    "or",
    "and",
]
I_OP_I = [
    "addi",
    "slti",
    "sltiu",
    "xori",
    "ori",
    "andi",
    "slli",
    "srli",
    "srai",
    "lb",
    "lh",
    "lw",
    "lbu",
    "lhu",
    "jalr",
]
I_OP_S = [
    "sb",
    "sh",
    "sw",
]
I_OP_U = [
    "lui",
    "auipc",
]
I_OP_B = [
    "beq",
    "bne",
    "blt",
    "bge",
    "bltu",
    "bgeu",
]
I_OP_J = [
    "jal",
]

M_OP_M = [
    "mul",
    "mulh",
    "mulhu",
    "mulhsu",
    "div",
    "divu",
    "rem",
    "remu",
]

# The rate of instruction type in the "body" program
# The sum of rates must equal to 100
[RV32_RATES]
# RV32I Base Integer Instruction Set
I_OP_R = 5
I_OP_I = 5
I_OP_S = 5
I_OP_U = 5
I_OP_B = 0
I_OP_J = 5

# M Extension for Integer Multiplication and Division
M_OP_M = 8

# V Standard Extension for Vector Operations
# Vector Integer Arithmetic Instructions
V_OPIVV = 8
V_OPIVX = 8
V_OPIVI = 8
V_OPMVV = 10
V_OPMVX = 11
# Configuration-Setting Instructions
V_OPCFG = 8
# Vector Loads and Stores
# Unit-stride
V_OP_UNIT_STRIDE = 7
# Unit-stride Fault-Only-First Loads
V_OP_FAULT_ONLY_FIRST_LOADS = 7
# Strided
V_OP_STRIDED = 0
# Indexed
V_OP_INDEXED = 0
